<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.iesalixar.daw2.jesusdelgado</groupId>
  <artifactId>dwese-ticket-logger-servlet</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>JESÚS DELGADO - Aplicación Web para el registro de tickets en compras de supermercado.</name>
  <url>https://github.com/jdelsan275</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <!-- Dependencia par el uso de Servlets -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>6.1.0</version>
      <scope>provided</scope> <!-- Esto indica que el contenedor del servidor (como Tomcat, Jetty, o cualquier servidor de aplicaciones compatible con Jakarta EE) proporcionará esta dependencia en tiempo de ejecución. -->
    </dependency>
    <!-- API de SLF4J -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.20</version>
    </dependency>
    <!-- Implementación de SLF4J (Logback) -->
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.6.4</version>
    </dependency>
    <!-- Implementación de JSTL necesaria para servidores como Tomcat -->
    <dependency>
      <groupId>org.glassfish.web</groupId>
      <artifactId>jakarta.servlet.jsp.jstl</artifactId>
      <version>3.0.1</version>
    </dependency>
    <!-- Dependencia par usar variables de entorno -->
    <dependency>
      <groupId>io.github.cdimascio</groupId>
      <artifactId>dotenv-java</artifactId>
      <version>3.0.2</version>
    </dependency>
    <!-- Dependencia par usar la base de datos MARIADB -->
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <version>3.5.10</version>
    </dependency>
    <!-- Dependencia LOMBOK -->
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.18.48</version>
        <scope>provided</scope>
      </dependency>
  </dependencies>
  <build>
    <finalName>dwese-ticket-logger-servlet</finalName>
    <plugins>
      <!-- Plugin para compilación de código fuente -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.16.0</version>
        <configuration>
          <source>24</source>
          <target>24</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.48</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <!-- Plugin para la generación de javadoc -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <configuration>
          <source>24</source>
          <additionalJOption>-Xdoclint:none</additionalJOption> <!-- Opcional: Ignora los errores de JavaDoc -->
          <encoding>UTF-8</encoding>
          <docencoding>UTF-8</docencoding>
          <charset>UTF-8</charset>
          <show>private</show> <!-- Incluye métodos privados en la documentación -->
          <noindex>false</noindex> <!-- Genera el índice de todos los elementos -->
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>javadoc</goal> <!-- El objetivo principal es generar JavaDoc -->
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Plugin de Servidor Jetty embebido -->
      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>11.0.26</version> <!-- Versión compatible con Jakarta EE 9+ -->
        <configuration>
          <webApp>
            <contextPath>/</contextPath>
          </webApp>
          <httpConnector>
            <port>8080</port>
          </httpConnector>
          <!-- Configuración para la depuración remota -->
          <jvmArgs>-Xdebug
            Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005</jvmArgs>
        </configuration>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>
</project>
